import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/Sidebar/Sidebar";
import Widget from "../components/Widget/Widget";
import Feed from "../components/Feed/Feed";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="grid grid-cols-9 h-screen overflow-hidden lg:max-w-6xl mx-auto">
        <Sidebar />
        <Feed />
        <Widget />
      </div>
    </>
  );
};

export default Home;
