import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/Sidebar/Sidebar";
import Image from "next/image";
import Widget from "../components/Widget";
import TweetBox from "../components/TweetBox/TweetBox";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Welcome to twitter app</h1>
      <Sidebar />
      <Widget />
      <TweetBox />
    </div>
  );
};

export default Home;
